services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TZ}
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ./config/config.json:/app/config/config.json
    ports:
      - "7435:7435"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "-f", "server"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shopsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pg_data:
